cmd: don't bind to nil flags
Currently our `main` branch is broken due the latest `spf13/viper`
upgrade to `v1.8.0`. Viper now returns an error if we try to bind to a
nil flag (flag's that are not yet defined).

Fixes the following error:

```
$ pscale
Error: flag for "org" is nil
````