auth: report better error messages
We don't tell the user what's wrong if their service tokens are missing, or if the service tokens are not set, but they forgot to authenticate via access tokens.

With service tokens misconfigured:

```
$ PLANETSCALE_SERVICE_TOKEN_ID="" PLANETSCALE_SERVICE_TOKEN="bar" go run cmd/pscale/main.go connect planetscale main

Error: not authenticated yet. Please run 'pscale auth login'
Error: both --service-token and --service-token-id are required for service token authentication
exit status 2
```

No service tokens are configured, access token is also missing :

```
$ go run cmd/pscale/main.go connect planetscale main

Error: not authenticated yet. Please run 'pscale auth login'
Error: --access-token is required for access token authentication
```