Switching to a harder error check within the `IsAuthenticated()` method
In this case if the service token values are provided in a swapped manner this extra error information will be output:
```
Error: not authenticated yet. Please run 'pscale auth login'
Error: the --service-token and --service-token-id values are swapped
```